import crypto from 'node:crypto';
import { promisify } from 'node:util';
import { config } from './config.js';
const scrypt = promisify(crypto.scrypt); const KEY_LENGTH = 64;
export async function hashPassword(password) { const salt = crypto.randomBytes(16).toString('hex'); const key = await scrypt(password, salt, KEY_LENGTH, { N: 16384, r: 8, p: 1 }); return `scrypt$${salt}$${key.toString('hex')}`; }
export async function verifyPassword(password, stored) { try { const [algorithm, salt, hex] = String(stored || '').split('$'); if (algorithm !== 'scrypt' || !salt || !hex) return false; const key = await scrypt(password, salt, KEY_LENGTH, { N: 16384, r: 8, p: 1 }); const expected = Buffer.from(hex, 'hex'); return expected.length === key.length && crypto.timingSafeEqual(expected, key); } catch { return false; } }
function ttlSeconds(value) { const match = String(value).match(/^(\d+)(s|m|h|d)?$/i); if (!match) return 28800; return Number(match[1]) * ({ s: 1, m: 60, h: 3600, d: 86400 }[String(match[2] || 's').toLowerCase()] || 1); }
function encode(value) { return Buffer.from(JSON.stringify(value)).toString('base64url'); }
export function signToken(claims) { const header = encode({ alg: 'HS256', typ: 'JWT' }); const now = Math.floor(Date.now() / 1000); const body = encode({ ...claims, iat: now, exp: now + ttlSeconds(config.jwtTtl) }); const unsigned = `${header}.${body}`; const signature = crypto.createHmac('sha256', config.jwtSecret).update(unsigned).digest('base64url'); return `${unsigned}.${signature}`; }
export function verifyToken(token) { const parts = String(token || '').split('.'); if (parts.length !== 3) throw new Error('Tokenformat ungueltig.'); const [header, body, signature] = parts; const unsigned = `${header}.${body}`; const expected = crypto.createHmac('sha256', config.jwtSecret).update(unsigned).digest(); const received = Buffer.from(signature, 'base64url'); if (expected.length !== received.length || !crypto.timingSafeEqual(expected, received)) throw new Error('Token-Signatur ungueltig.'); const claims = JSON.parse(Buffer.from(body, 'base64url').toString('utf8')); if (!claims.exp || claims.exp <= Math.floor(Date.now() / 1000)) throw new Error('Token abgelaufen.'); return claims; }
export function authMiddleware(req, res, next) { const header = req.headers.authorization || ''; if (!header.startsWith('Bearer ')) return res.status(401).json({ error: 'AUTH_REQUIRED', message: 'Anmeldung erforderlich.' }); try { req.user = verifyToken(header.slice(7)); return next(); } catch { return res.status(401).json({ error: 'INVALID_TOKEN', message: 'Anmeldung ist ungueltig oder abgelaufen.' }); } }
export function requirePermission(permission) { return (req, res, next) => { if (!req.user?.permissions?.includes(permission)) return res.status(403).json({ error: 'FORBIDDEN', message: 'Fuer diese Aktion fehlt die Berechtigung.' }); return next(); }; }
export function requireAnyPermission(...permissions) { return (req, res, next) => { if (!permissions.some(permission => req.user?.permissions?.includes(permission))) return res.status(403).json({ error: 'FORBIDDEN', message: 'Fuer diese Aktion fehlt die Berechtigung.' }); return next(); }; }
